name: e2e

on:
  pull_request:
    branches:
      - main
      - release-2.[5-9]
  push:
    branches:
      - main
      - release-2.[5-9]

jobs:
  kind-tests:
    uses: ./.github/workflows/fw-kind-tests.yml
