name: Framework KinD Workflow

on:
  workflow_call:
    inputs:
      hub_only_component:
        required: false
        type: string
        default: 'false'

env:
  RELEASE_BRANCH: ${{ github.event.pull_request.base.ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Tests # Part of the check name, be careful when changing.

    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    strategy:
      # Don't skip all tests if one fails - others may still have useful info
      fail-fast: false
      matrix:
        # Run tests against an old and a new version of kubernetes
        # (for reference, OCP 4.6 runs Kubernetes v1.19)
        # KinD tags are listed at https://hub.docker.com/r/kindest/node/tags
        kind:
          - 'minimum' # defined in the common makefile
          - 'latest'
        deployOnHub:
          - 'true'
          - 'false'
        hosted:
          - 'hosted'
          - '' # empty strings won't appear in the check name
        
        # Just add one hosted mode test.
        exclude:
          - hosted: 'hosted'
        include:
          - kind: 'latest'
            deployOnHub: 'false'
            hosted: 'hosted'

    steps:
    - name: Checkout Component Repository
      # Checkout a specific component when called from another repository
      if: ${{ github.event.repository.name != 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        # `repository` is inferred as the "caller" repository 
        path: component
        # `ref` is inferred as the new commit in the "caller" repository

    - name: Checkout Policy Framework
      # Checkout a stable branch when called from another repository
      if: ${{ github.event.repository.name != 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        repository: stolostron/governance-policy-framework
        path: framework
        ref: ${{ env.RELEASE_BRANCH }} # like main or release-*

    - name: Checkout Policy Framework
      # Checkout like "usual" when called from this repository
      if: ${{ github.event.repository.name == 'governance-policy-framework' }}
      uses: actions/checkout@v3
      with:
        # `repository` is inferred as the "caller" repository 
        path: framework
        # `ref` is inferred as the new commit

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: framework/go.mod

    - name: Verify modules
      if: ${{ github.event.repository.name == 'governance-policy-framework' }}
      working-directory: framework
      run: |
        go mod verify
        
    - name: Verify format
      if: ${{ github.event.repository.name == 'governance-policy-framework' }}
      working-directory: framework
      run: |
        make fmt
        git diff --exit-code
        make lint
    
    - name: Patch Component Image (addon-controller, hosted)
      # The Framework's Make target will use this version of the addon-controller to deploy components for hosted mode
      if: ${{ matrix.hosted == 'hosted' && github.event.repository.name == 'governance-policy-addon-controller' }}
      uses: actions/checkout@v3
      with:
        # `repository` is inferred as the "caller" repository 
        path: framework/governance-policy-addon-controller
        # `ref` is inferred as the new commit
  
    - name: Bootstrap the KinD Cluster
      working-directory: framework
      env:
        deployOnHub: ${{ matrix.deployOnHub }}
        KIND_VERSION: ${{ matrix.kind }}
        HOSTED: ${{ matrix.hosted }}
      run: |
        echo "::group::make e2e-dependencies"
        make e2e-dependencies
        echo "::endgroup::"

        echo "::group::bootstrap"
        if [[ "${HOSTED}" == "hosted" ]]; then
          make kind-bootstrap-hosted
        else
          make kind-bootstrap-cluster
        fi
        echo "::endgroup::"

        echo "::group::pods on hub"
        KUBECONFIG=$(pwd)/kubeconfig_hub kubectl get pods -A
        echo "::endgroup::"

        echo "::group::pods on managed"
        KUBECONFIG=$(pwd)/kubeconfig_managed kubectl get pods -A
        echo "::endgroup::"

        echo "::group::Saving kubeconfig paths for use in other steps"
        echo "MANAGED_KUBECONFIG=$(pwd)/kubeconfig_managed" | tee -a $GITHUB_ENV
        echo "HUB_KUBECONFIG=$(pwd)/kubeconfig_hub" | tee -a $GITHUB_ENV
        echo "HUB_INTERNAL_KUBECONFIG=$(pwd)/kubeconfig_hub_internal" | tee -a $GITHUB_ENV
        echo "::endgroup::"

    - name: Patch Component Image
      if: ${{ github.event.repository.name != 'governance-policy-framework' && matrix.hosted == '' }}
      working-directory: component
      env:
        deployOnHub: ${{ matrix.deployOnHub }}
        HUB_ONLY: ${{ inputs.hub_only_component }}
      run: |
        if [[ "$RELEASE_BRANCH" != "main" ]]; then
          export TAG=latest-$(echo $RELEASE_BRANCH | cut -d'-' -f 2):
        else
          export TAG=latest
        fi

        export MANAGED_CONFIG=${MANAGED_KUBECONFIG}
        export HUB_CONFIG=${HUB_KUBECONFIG}
        export HUB_CONFIG_INTERNAL=${HUB_INTERNAL_KUBECONFIG}

        if [[ "${deployOnHub}" == "true" ]] || [[ "${HUB_ONLY}" == "true" ]]; then
          export WATCH_NAMESPACE=managed
          export KIND_NAME=hub
          export KUBECONFIG=${HUB_KUBECONFIG}
        else
          export WATCH_NAMESPACE=managed
          export KIND_NAME=managed
          export KUBECONFIG=${MANAGED_KUBECONFIG}
        fi

        echo "Using TAG=${TAG}, WATCH_NAMESPACE=${WATCH_NAMESPACE}, KIND_NAME=${KIND_NAME}, KUBECONFIG=${KUBECONFIG}"

        echo "::group::make build-images"
        make build-images
        echo "::endgroup::"

        echo "::group::make kind-deploy-controller-dev"
        make kind-deploy-controller-dev
        echo "::endgroup::"

    - name: Patch Component Image (hosted)
      if: ${{ github.event.repository.name != 'governance-policy-framework' && github.event.repository.name != 'governance-policy-addon-controller' && matrix.hosted == 'hosted' }}
      working-directory: component
      env:
        deployOnHub: ${{ matrix.deployOnHub }}
        HUB_ONLY: ${{ inputs.hub_only_component }}
      run: |
        # this image won't actually pushed to quay:
        export IMAGE_NAME_AND_VERSION=quay.io/governance-policy-framework/component

        echo "::group::build and load image"
        make build-images
        export NEW_IMAGE="${IMAGE_NAME_AND_VERSION}:latest"
        kind load docker-image "${NEW_IMAGE}" --name policy-addon-ctrl1
        echo "::endgroup::"

        export KUBECONFIG=${HUB_KUBECONFIG}

        echo "::group::hub pods"
        KUBECONFIG=${HUB_KUBECONFIG} kubectl get pods -A -o 'custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,PHASE:.status.phase,STARTED:.status.startTime,IMAGE:.spec.containers[0].image'
        echo "::endgroup::"
        echo "::group""managed pods"
        KUBECONFIG=${MANAGED_KUBECONFIG} kubectl get pods -A -o 'custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,PHASE:.status.phase,STARTED:.status.startTime,IMAGE:.spec.containers[0].image'
        echo "::endgroup::"

        if [[ "${HUB_ONLY}" == "true" ]]; then
          # Must be the propagator
          kubectl -n open-cluster-management set image deployment/governance-policy-propagator "governance-policy-propagator=${NEW_IMAGE}"
          kubectl -n open-cluster-management rollout status deployment/governance-policy-propagator --timeout=300s || echo "warning, rollout may have failed"
        else        
          echo "::group::update the addon-controller to use the new image"
          # component "foo-bar" becomes "FOO_BAR_IMAGE": 
          export IMAGE_ENV="$(tr "[:lower:]-" "[:upper:]_" < COMPONENT_NAME)_IMAGE"

          kubectl -n governance-policy-addon-controller-system set env deployment/policy-addon-ctrl-controller-manager "${IMAGE_ENV}=${NEW_IMAGE}"
          kubectl -n governance-policy-addon-controller-system set env deployment/policy-addon-ctrl-controller-manager --list
          kubectl -n governance-policy-addon-controller-system rollout status deployment/policy-addon-ctrl-controller-manager --timeout=300s || echo "warning, rollout may have failed"
          echo "::endgroup::"
        fi
        
        echo "::group::hub pods"
        KUBECONFIG=${HUB_KUBECONFIG} kubectl get pods -A -o 'custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,PHASE:.status.phase,STARTED:.status.startTime,IMAGE:.spec.containers[0].image'
        echo "::endgroup::"
        echo "::group""managed pods"
        KUBECONFIG=${MANAGED_KUBECONFIG} kubectl get pods -A -o 'custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,PHASE:.status.phase,STARTED:.status.startTime,IMAGE:.spec.containers[0].image'
        echo "::endgroup::"

    - name: Run e2e tests
      working-directory: framework
      env:
        TEST_ARGS: --json-report=report.json --junit-report=report.xml --output-dir=test-output
        HOSTED: ${{ matrix.hosted }}
      run: |
        if [[ "${HOSTED}" == "hosted" ]]; then
          make e2e-test-hosted
        else
          make e2e-test
        fi

    - name: Debug
      if: ${{ failure() }}
      working-directory: framework
      run: |
        make e2e-debug-kind
        tar -czvf e2e-debug.tar.gz test-output/debug

    - name: Upload Debug Artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: fw-kind-debug-${{ matrix.kind }}-${{ matrix.deployOnHub }}
        path: framework/e2e-debug.tar.gz

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: fw-kind-report-${{ matrix.kind }}-${{ matrix.deployOnHub }}${{ matrix.hosted == 'hosted' && '-hosted' }}
        path: |
          framework/test-output/report.xml
          framework/test-output/report.json
